name: Release creation

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Prep Release
        id: get_latest_release
        run: |
          curl --silent latest_version="https://api.github.com/repos/hdescottes/GdxGame/releases/latest" |
          grep -Po "(?<=\"tag_name\": \").*(?=\")" >> $env:GITHUB_OUTPUT
#      - name: Get version
#        id: get_version
#        run:
      - name: test version
        run: echo "${{ steps.get_latest_release.outputs.latest_version }}"

          # Parse changelog

#      - name: Create Release
#        id: create_release
#        uses: actions/create-release@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ env.RELEASE_VERSION }}
#          release_name: Release ${{ env.RELEASE_VERSION }}
#          body: ${{ env.GITHUB_ENV.changelog }}
#          draft: false
#          prerelease: true